// console.log(validator.isURL("www.google.com"))
// console.log(validator.isURL("https://www.google.com"))
// console.log(validator.isURL("functionup.org"))
// console.log(validator.isURL("functionup.orgi12345"))
// console.log(validator.isURL("123"))
// console.log(validator.isURL("https://www.amazon.com"))
// console.log(validator.isURL("https://www.amazon.commmmmmmmmmm"))
// console.log(validator.isURL("https://wwwwwwwwwwww.amazon.commmmmmmmmmm"))
// console.log(validator.isURL("https://xyz.amazon.commmmmmmmmmm"))

// console.log(validUrl.isUri("www.google.com"))
// console.log(validUrl.isUri("https://www.google.com"))
// console.log(validUrl.isUri("functionup.org"))
// console.log(validUrl.isUri("functionup.orgi12345"))
// console.log(validUrl.isUri("123"))